server:
  global:
    scrape_interval: 10s
    scrape_timeout: 8s
    evaluation_interval: 10s
  ingress:
    enabled: true
    ingressClassName: haproxy
    hosts:
      - prometheus.fosscut.com
    tls:
      - secretName: prometheus.fosscut.com-tls-secret
        hosts:
          - prometheus.fosscut.com

# Configure scraping only for selected namespaces
# kubernetes-pods* scrapes only /metrics endpoint of pods
# kubernetes-nodes-cadvisor scrapes cAdvisor (cpu/memory/disk/network) metrics
# for all pods on all nodes
scrapeConfigs:
  kubernetes-api-servers:
    enabled: false
  kubernetes-nodes:
    enabled: false
  kubernetes-nodes-cadvisor:
    enabled: true
  kubernetes-service-endpoints:
    enabled: false
  kubernetes-service-endpoints-slow:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  kubernetes-services:
    enabled: false
  kubernetes-pods:
    enabled: false
  kubernetes-pods-slow:
    enabled: false

# Disable unnecessary components
alertmanager:
  enabled: false

kube-state-metrics:
  enabled: false

prometheus-node-exporter:
  enabled: false

prometheus-pushgateway:
  enabled: false
